import{a as m,S as L,i as c}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const h=s=>`<li class="gallery-card">
    <a class="gallery-link" href="${s.largeImageURL}"> <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" /></a>
           <div class="gallery-info">
                <p class="likes">Likes <span>${s.likes}</span></p>
                <p class="views">Views <span>${s.views}</span></p>
                <p class="comments">Comments <span>${s.comments}</span></p>
                <p class="downloads">Downloads <span>${s.downloads}</span></p>
            </div>    
            </li>`;m.defaults.baseURL="https://pixabay.com/api/";const y=(s,t)=>{const o={params:{key:"32552782-0d4c86680018457e820f20492",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}};return m.get("",o)},d=document.querySelector(".js-search-form"),p=document.querySelector(".js-gallery"),g=document.querySelector(".js-loader"),u=document.querySelector(".js-load-more");let n=1,i="";const v=15;let f=new L(".gallery-link");const b=()=>{g.classList.remove("is-hidden")},w=()=>{g.classList.add("is-hidden")},P=async s=>{try{if(s.preventDefault(),i=d.elements.user_query.value.trim(),!i){c.error({message:"Please enter a search query.",position:"topRight"});return}n=1,b();const t=await y(i,n);if(console.log(t),w(),t.data.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p.innerHTML="",d.reset();return}const o=t.data.hits.map(a=>h(a)).join("");p.innerHTML=o,u.classList.remove("is-hidden"),f.refresh()}catch(t){console.log(t)}},S=async s=>{try{n++;const t=await y(i,n),o=t.data.hits.map(r=>h(r)).join("");p.insertAdjacentHTML("beforeend",o);const a=t.data.totalHits,e=Math.ceil(a/v);n===e&&(u.classList.add("is-hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),f.refresh()}catch(t){console.log(t)}};d.addEventListener("submit",P);u.addEventListener("click",S);
//# sourceMappingURL=index.js.map
