import{a as d,S as u,i as l}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m=s=>`<li class="gallery-card">
    <a class="gallery-link" href="${s.largeImageURL}"> <img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" /></a>
           <div class="gallery-info">
                <p class="likes">Likes <span>${s.likes}</span></p>
                <p class="views">Views <span>${s.views}</span></p>
                <p class="comments">Comments <span>${s.comments}</span></p>
                <p class="downloads">Downloads <span>${s.downloads}</span></p>
            </div>    
            </li>`;d.defaults.baseURL="https://pixabay.com/api/";const h=s=>{const t={params:{key:"32552782-0d4c86680018457e820f20492",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return d.get("",t)},i=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),p=document.querySelector(".js-loader");let y=new u(".gallery-link");const f=()=>{p.classList.remove("is-hidden")},g=()=>{p.classList.add("is-hidden")},L=async s=>{try{s.preventDefault();const t=i.elements.user_query.value.trim();if(!t){l.error({message:"Please enter a search query.",position:"topRight"});return}f();const o=await h(t);if(console.log(o),g(),o.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.innerHTML="",i.reset();return}const a=o.data.hits.map(e=>m(e)).join("");c.innerHTML=a,y.refresh()}catch(t){console.log(t)}};i.addEventListener("submit",L);
//# sourceMappingURL=index.js.map
