import{a as p,S as h,i}from"./assets/vendor-CZwys2ms.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const m=r=>`<li class="gallery-card">
    <a class="gallery-link" href="${r.largeImageURL}"> <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" /></a>
           <div class="gallery-info">
                <p class="likes">Likes <span>${r.likes}</span></p>
                <p class="views">Views <span>${r.views}</span></p>
                <p class="comments">Comments <span>${r.comments}</span></p>
                <p class="downloads">Downloads <span>${r.downloads}</span></p>
            </div>    
            </li>`,f="https://pixabay.com/api/",g=r=>{const o=new URLSearchParams({key:"32552782-0d4c86680018457e820f20492",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"});return console.log(o.toString()),fetch(`${f}?${o}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})};p.get("/users").then(r=>{console.log(r.data)});const l=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),d=document.querySelector(".js-loader");let y=new h(".gallery-link");const L=()=>{d.classList.remove("is-hidden")},u=()=>{d.classList.add("is-hidden")},w=r=>{r.preventDefault();const o=l.elements.user_query.value.trim();if(!o){i.error({message:"Please enter a search query.",position:"topRight"});return}L(),g(o).then(s=>{if(u(),s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.innerHTML="",l.reset();return}const a=s.hits.map(e=>m(e)).join("");c.innerHTML=a,y.refresh()}).catch(s=>{u(),console.log(s)})};l.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
